paths:
  outputs_root: outputs   # 训练/评估产物根目录（lora、processor、logs、figures、checkpoints）

model:
  base_id: Qwen/Qwen2.5-VL-3B-Instruct

lora:
  r: 16
  alpha: 32
  dropout: 0.05
  bias: "none"
  target_modules:
    - self_attn.q_proj
    - self_attn.k_proj
    - self_attn.v_proj
    - self_attn.o_proj
    - mlp.gate_proj
    - mlp.up_proj
    - mlp.down_proj
  modules_to_save:
    - lm_head

data:
  name: FD001

  # === 新增：默认预处理设置 ===
  preprocess:
    raw_dir: data/raw                    # 原始 C-MAPSS 数据路径
    out_dir: data/processed              # 输出路径 (预处理结果 npy)
    rearley: 125                         # RUL 截断上限
    window_size: auto                    # FD001=30, FD002=20, FD003=30, FD004=15
    step: 1                              # 滑动步长
    test_last_window: true               # 测试集仅保留每台发动机最后一个窗
    scale_mode: minmax                   # Min–Max [-1,1]（论文通用）
    select14: false                      # 是否保留14个有效传感器（默认false）
  # ==================================

  # 训练/评估阶段读取图像数据的路径
  train_dir: data/images/FD001/train
  test_dir:  data/images/FD001/test
  image_glob: sample_*.png
  renderer: ${data.imgify.renderer}
  label_filename: y.npy
  image_size: 448
  seed: 42
  train_ratio: 0.8     # 若单目录切分时使用

  # === 图像化配置（mmts.cli.imgify） ===
  imgify:
    renderer: grayscale
    orientation: row-major
    flip_vertical: false
    flip_horizontal: false

    # === 默认使用预处理后的缩放结果 ===
    scale_mode: none          # 不再在 imgify 阶段做缩放（预处理已完成）
    pmin: 1
    pmax: 99
    patch_window: 20
    patch_stride: 1
    cmap: rainbow
    # =======================================

    train:
      x_npy: data/processed/FD001/X_train.npy
      y_npy: data/processed/FD001/y_train.npy
      out_dir: data/images/FD001/train
      max_samples: 100

    test:
      x_npy: data/processed/FD001/X_test.npy
      y_npy: data/processed/FD001/y_test.npy
      out_dir: data/images/FD001/test
      max_samples: null
  # =======================================

train:
  epochs: 3
  batch_size: 1
  grad_accum: 8
  lr: 2e-4
  weight_decay: 0.01
  warmup_ratio: 0.05
  scheduler: cosine
  logging_steps: 10
  save_strategy: epoch
  bf16: true
  fp16: false
  grad_ckpt: true
  allow_tf32: true

eval:
  lora_dir: null
  processor_dir: null
  
  # 生成超参
  max_new_tokens: 32
  do_sample: false
  num_beams: 1

  # RUL 合法区间（解析与裁剪）
  rul_low: 0.0
  rul_high: 125.0

  image_size: ${data.image_size}

  metrics:
    - rmse
    - mae
    - r2
    - valid_ratio

prompts:
  rules_file: configs/base_rules.txt
